Use naptan api #183
ONSdigital/SDG_11.2.1 pull request #185
Opened 2022-03-03 15:13 UTC by Antonio-John

-This tickets look to retrieve stops data from the [NaPTAN wesbite.](https://naptan.api.dft.gov.uk/swagger/index.html) and save in the data folder, then as a feather.
-Downloads data and saves as feather if the local copy of stops data is more then 28 days old.

2022-03-04 13:56 UTC, jwestw requested changes
Please take a look at the comments and action what you want there. Please also run a linter.

2022-03-04 13:56 UTC, jwestw commented on SDG_11.2.1_main.py
> +today = datetime.now().strftime('%Y%m%d')
Where is this variable used?

If it's used in the data ingest file should it be defined there?

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
>      absolute_path=os.path.join(dir,csv_file)
Not sure who coded this (possibly me) but just noticing some pep8 compliance stuff here. 

`absolute_path=os.path.join(dir,csv_file)`

should be 

`absolute_path = os.path.join(dir, csv_file)

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
> +def _get_stops_from_api(url,file_name):
This looks great!

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
> +    csv_file = open(file_name, 'wb')
any reason you didn't use `with open` here?

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
> +    return csv_file
Should this return anything? Contradicts your docstring

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
> +    file_list=os.listdir(dir)
`file_list=os.listdir(dir)`

should be

`file_list = os.listdir(dir)`

Look into using a linter in VS code to automatically do this stuff for you. If you want to go further, look into pre-commits. 

There is other pep-8 stuff which I won't comment on. Just try running a linter :)

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
> +    # get's a list of files from the directory
Maybe spread out these comments so they are above the code they are describing

2022-03-04 13:56 UTC, jwestw commented on data_ingest.py
> +def get_stops_file(url, file_name, dir):
Very nice entry point function.

2022-03-04 14:57 UTC, Antonio-John commented on SDG_11.2.1_main.py
> +today = datetime.now().strftime('%Y%m%d')
Have moved this into the data ingest file

2022-03-04 17:17 UTC, Antonio-John commented
I have rebase with master and think this is ready to merge. Please let me know if you spot any further problems :) @jwestw

2022-03-04 17:19 UTC, Antonio-John commented on data_ingest.py
> +    csv_file = open(file_name, 'wb')
Not sure, i think the only difference is I have to manually close the file. Some more info here https://www.pythonforbeginners.com/files/with-statement-in-python

2022-03-04 20:38 UTC, jwestw approved these changes

2022-03-04 20:43 UTC, jwestw commented
Hi @Antonio-John I am getting a file not found error because I don't have ".../SDG_11.2.1/data/stops"

Could you give me some instructions for testing here? Thanks

2022-03-07 08:46 UTC, Antonio-John commented
> Hi @Antonio-John I am getting a file not found error because I don't have ".../SDG_11.2.1/data/stops"
> 
> Could you give me some instructions for testing here? Thanks

Thanks for reviewing/Running.

I have uploaded to the FTP server the stops directory with an initial stops data file. I kind of assumed that the FTP transfer server would be working within the pipeline here for others. 

Are you able to run that code to get the directory/initial file or transfer manually?

2022-03-09 16:59 UTC, jwestw commented
Looking good.

2022-03-09 16:59 UTC, merged