Document env #134
ONSdigital/SDG_11.2.1 pull request #190
Opened 2022-03-25 16:54 UTC by paigeh1

I have finished updating the README.md with new documentation and linked tutorials that I found to be useful. Happy for suggestions or if it needs further updating.

2022-03-29 13:19 UTC, jwestw requested changes
This is a really great addition to the README! Just a few questions and suggested changes.

2022-03-29 13:19 UTC, jwestw commented on README.md
> +You should now have your SSH key set up. To clone the repository, we need to first go to the project directory (where you would like it saved on your desktop).
Do you think the word "desktop" might be misleading here? For many people that would mean the actual OS Desktop space, but to others might mean their own computer (i.e. desktop computer). I am not quite sure which one you mean here, so I suggest using "local computer" if you mean that. or "local drive" maybe if you mean that.

2022-03-29 13:19 UTC, jwestw commented on README.md
> +    $ cd C:\Users\name\project-directory
Note, this is Windows specific (and I think this might vary depending on your Windows installation and settings, so just state this is an example). You don't have to specify where Linux/Mac users need to save to, but suggest they find a similarly suitable directory in their "home" folder. 

Also, maybe there should be a step before this. Something like "Create a new project directory", and tell the user to create a folder called "programming" or "repos" to clone to.

2022-03-29 13:19 UTC, jwestw commented on README.md
> -`conda activate SDG_11.2.1`
I think you don't cover the activation of the environment. Do you think this is superfluous for the README, or worth including?

2022-04-01 14:48 UTC, paigeh1 commented on README.md
> +You should now have your SSH key set up. To clone the repository, we need to first go to the project directory (where you would like it saved on your desktop).
I am going to change this to local drive

2022-04-01 14:53 UTC, paigeh1 commented on README.md
> +You should now have your SSH key set up. To clone the repository, we need to first go to the project directory (where you would like it saved on your desktop).
Changed made with [this commit ](https://github.com/ONSdigital/SDG_11.2.1/pull/190/commits/a95f60190bbdf9aafbba4b3fb5c9d4da0924669c)

2022-04-01 14:59 UTC, paigeh1 commented on README.md
> +    $ cd C:\Users\name\project-directory
I have noted this is for Windows only and mentioned that the project directory is where you like it saved to on your local drive.

2022-04-01 15:29 UTC, paigeh1 commented on README.md
> -`conda activate SDG_11.2.1`
I have added the windows command without the conda path in the windows path environment and linked to the tutorial again required to do this.

2022-04-01 15:32 UTC, jwestw commented
That's great. Thanks @paigeh1

2022-04-01 15:33 UTC, merged