Fix:205 bug in acquiring stopsfeather
ONSdigital/SDG_11.2.1 pull request #234
Opened 2022-06-10 15:01 UTC by james-westwood

Fixes #205 

Thanks to great help from @nkshaw23 we have managed to get the bug sorted. 

A better and more robust solution might involve integrating the API calls and 28 day check into the `any_to_pd` function but what we have created here is sufficiently robust and runs fine.

2022-06-14 16:28 UTC, paigeh1 commented
@jwestw We ran this first time and had "Angus" as our LA, where we received an error on line 288 (when changing the number of disabled into an integer). This error was: `Cannot convert non-finite values (NA or inf) to integer`

We believe this to be because the LA_df does not have all the local authorities in the dataset! We have ran this with 2019 and 2020 as our calculation years and it seems to have the same issue. We will create a ticket explaining this more.

2022-06-14 16:42 UTC, paigeh1 requested changes
Look at the issue comments as all info is there.

2022-06-16 13:17 UTC, james-westwood commented
I think problems like this could be avoided more easily if this module was re-written in OOP. Then we could share a parameter like `self.stops_path` amongst the different methods in this context.

I made a ticket about this ages ago (https://github.com/ONSdigital/SDG_11.2.1/issues/85), and also attempted the re-write a while back, but found that it was a bit too much of a lengthy task to take on myself while there was so much else to get on with.

2022-06-24 08:45 UTC, Antonio-John approved these changes
Approved as stops path has been updated.

2022-06-24 08:46 UTC, jwestw commented
Merging without Paige re-approving as the requested changes have been made but Paige is away.

2022-06-24 08:47 UTC, merged