264 scotland by disability status
ONSdigital/SDG_11.2.1 pull request #287
Opened 2022-08-19 16:03 UTC by paigeh1

Disability data is now in the Scotland results dataframe. Let me know if you have any questions or are struggling with accessing the data.

**Note: The ordering of the dataframe is currently incorrect. This will be fixed when we have all disaggregations and can use the `do.reorder_final_df` function**

Outputted data frame below:
![image](https://user-images.githubusercontent.com/102051068/185659861-2085c37e-e8ad-40e3-b98c-14cfa01da00b.png)

2022-08-22 10:03 UTC, Antonio-John requested changes

2022-08-22 10:03 UTC, Antonio-John commented on SDG_scotland.py
> +    )
I think a lot of this logic could be functionalised. As this is happening in both the England&Wales, here and potentially in NI. It would be good to have 1 single function maybe in data transform that would do this.

2022-08-22 10:03 UTC, Antonio-John commented on SDG_scotland.py
> +                                             "data",
I think it would be clearer if we created a disability directory within data. so it would be data/disability_status/QS303_scotland.csv

2022-08-26 10:13 UTC, paigeh1 commented
@Antonio-John I have taken your feedback on board and have put in a function (`disab_disagg`) for the disability disaggregation for both Scotland and England&Wales. I needed to change a couple column names for Scotland for the function to work. I also moved the loading in `disability_df` to outside the loop for both England&Wales and Scotland for efficiency for both. Finally, the folder "disability_status" was created and now includes **both nomis_QS303 and QS303_scotland** and this was changed in both scripts. I will be putting the Scotland data we have acquired in Sync for everyone to access. Any further comments are welcome :)

2022-09-02 07:46 UTC, Antonio-John commented
Thanks for making those changes @paigeh1 . Just a couple of comments.
- Does```la_pop_df = dt.disab_disagg(disability_df, la_pop_df)``` have to happen within the for loop? Could it be done once for all areas outside of the for loop?
- #206 created a row which had the population of a local authority. This has been merged into master. Not sure this is feeding into your code, based on the outputs I'm seeing? Could you look into this please?
- When this is approved @james-westwood & @nkshaw23 you will need to create a folder within data called disability_status. This will contain both the QS303 files for England&Wales and Scotland.

2022-09-02 10:41 UTC, paigeh1 commented
Thanks a lot Antonio for looking at this again! Got a couple comments:

- It can happen outside I think, we would have to merge disability_df and the population df outside the for loop as well, then split this into local authorities in the loop. My only inclination against it currently is all other disaggregations are calculated inside the for loop and I'm not sure if it would help efficiency currently because we would have to do it for all local authorities at once (so the whole population dataframe), rather than one at a time (which we are only calculating one currently for testing). I'm happy to have a chat about it if you think it's worthwhile!
- I think that the pull request had been approved but not merged in when I finished the code. I've rebased and checked that it includes a total pop line :)

2022-09-02 10:55 UTC, Antonio-John commented
I agree with you on the dt.disab_disagg(disability_df, la_pop_df).
Code & outputs look great. I am happy to approve for merge.

2022-09-02 10:56 UTC, Antonio-John approved these changes

2022-09-02 10:57 UTC, merged