Create pull_request_template.md
ONSdigital/SDG_11.2.1 pull request #300
Opened 2022-09-01 13:39 UTC by jwestw

This isn't linked to an issue. 

This PR should create a markdown template that will automatically appear in the first comment in each pull request that is made - which should help both the developer submitting the PR and the reviewer.

Template is adapted from: https://best-practice-and-impact.github.io/qa-of-code-guidance/peer_review.html

2022-09-02 12:41 UTC, nkshaw23 commented on .github/pull_request_template.md
> +    - [ ] Code has been linted
Potentially add a bit about best way to do this e.g. install pylint in vs_code

2022-09-02 12:43 UTC, nkshaw23 commented on .github/pull_request_template.md
> +
You mentioned this earlier I think - section on adding any data to sync if its required to run

2022-09-02 14:08 UTC, Antonio-John commented on .github/pull_request_template.md
> +
I think a bullet like this in peer review. Maybe obvious but might be good to have as a check box.
-  [ ] Code runs successfully

2022-09-02 14:44 UTC, paigeh1 requested changes
Looks good, left one comment and agree with both @Antonio-John and @nkshaw23 on their comments.

2022-09-02 14:44 UTC, paigeh1 commented on .github/pull_request_template.md
> +- [ ] Doctrings has been created and accurately describes the function's functionality
Might also be worth writing what format we use for docstrings. Think we have to use [Google style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for them to render in github pages.

2022-10-21 08:20 UTC, jwestw commented
Should also have a bullet point about documentation (at least notes on what's been changed)

2022-11-04 13:56 UTC, james-westwood commented on .github/pull_request_template.md
> +    - [ ] Code has been linted
I think this should be in the "For developers" section of the readme

2022-11-04 13:57 UTC, james-westwood commented on .github/pull_request_template.md
> +
Done!

2022-11-04 14:18 UTC, james-westwood commented on .github/pull_request_template.md
> +
Done

2022-11-04 14:32 UTC, Antonio-John approved these changes

2022-11-04 14:32 UTC, Antonio-John commented on .github/pull_request_template.md
> +#### Closes or fixes
Very small comment. Could you put some more detail in here e.g *Insert issue/card number this closes/fixes* please?

2022-11-11 09:13 UTC, paigeh1 approved these changes
Happy to approve

2022-11-11 09:14 UTC, merged