WIP: 67 find the urbanrural classification data by output area for scotland
ONSdigital/SDG_11.2.1 pull request #301
Opened 2022-09-02 10:32 UTC by Antonio-John

This is produces new estimates for transport accessibility disaggregated by urban/rural population.

The new data source is contained within data/urban_rural/scotland/
and can be downloaded [here](https://www.isdscotland.org/Products-and-Services/GPD-Support/Geography/Urban-Rural-Classification/).

I have uploaded these to the sync website.

I will wait for #287 to be closed before merging. There are likely to be conflicts, so I will solve them after that is merged then request a review from @paigeh1 afterwards.

Closes #249

2022-09-02 13:32 UTC, Antonio-John commented
I have solved the conflicts & working. Ready for review whenever you have capacity. @paigeh1

2022-09-09 13:05 UTC, paigeh1 requested changes
Really great work on this! I have put a couple comments. As mentioned, I think there is duplicate code and it could be useful to have a function as mentioned to improve both scripts :)

2022-09-09 13:05 UTC, paigeh1 commented on SDG_scotland.py
> +    urb_df = only_la_pwc_with_pop[only_la_pwc_with_pop.urb_rur_class == "urban"]
A lot of this is a repeat of what it is in E&W. Can we make an urban rural function similar to disability?

2022-10-21 12:22 UTC, paigeh1 approved these changes
Happy to approve :) Can you put info in Nathan's document on the data you have found so it is in one place please? Don't think it is stored elsewhere

2022-10-28 07:25 UTC, merged