304 produce aggregate estimate ni
ONSdigital/SDG_11.2.1 pull request #357
Opened 2022-12-09 15:39 UTC by paigeh1

## Pull Request submission 

I have put the aggregate estimate for NI here. I have not addressed all of the tasks in the ticket, see #356, this will be done in another ticket.

As part of this ticket, I have downloaded a new package to convert latitude and longitude coordinates to BNG. For this, you need to install the package convertbng, which is also in the requirements.txt.

I would redownload all NI datasets to run this ticket as the majority of NI data has changed quite a bit over recent weeks.

I still need to write some methodological changes here and will edit here when this has been done.

#### Closes or fixes

Fixes #

#### Code

- [ ] **Requirements** My/our code matches the requirements of the ticket
- [ ] **Functionality**: New functions meet requirements in issue ticket
- [ ] **Compliant Code** Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
- [ ] **Code runs** The code runs on my machine
- [ ] **Clean Code** 
    - [ ] Code has been linted (use your favourite linter)
    - [ ] Code adheres to [DRY]([url](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) 

#### Documentation

Any new code includes all the following forms of documentation:

- [ ] **Function Documentation** Docstrings within the function(s') definition(s) have been created
    - [ ] Includes `parameters` and `returns` for all major functions 
    - [ ] Includes data types
- [ ] **Updated Documentation**: Working doc has been updated and a new ticket to update the master documentation has been created. 

#### Data
- [ ] All data needed to run this script has been added to Sync

#### Testing
- [ ] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_

---

# Peer Review Section

- [ ] All requirements install from (updated) `requirements.txt`
- [ ] Documentation has been created and is clear - check the google Doc
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

2022-12-19 10:38 UTC, nkshaw23 commented on SDG_NI.py
>  whole_NI_df = pd.read_csv(os.path.join(CWD, "data", "KS101NI.csv"),
Reduced extra columns and removed `,` in thousands for this dataset - also restricted to just the columns you filter too anyway. This reduced file size from 70mb to 200 kb.

Suggest we read in this dataset and then remove lines 70 -75 and update variable in 67 to `census_df`

2022-12-19 10:45 UTC, nkshaw23 commented on SDG_NI.py
> +stops_geo_df = di.geo_df_from_pd_df(pd_df=stops_df,
Think this process should be changed a bit and match `main` and `scotland`. This might well sort the (very minor) misalignment issue (#352).

Suggested steps:

1) Update Easting and Northing columns to correct values on sync
2) Read this dataset into `geo_df_from_pd_df` using Easting, Northing and `DEFAULT_CRS` from config.yaml.

Think docstring can then be updated to remove mention of latitude and longitude (as we are loading and setting in BNG)

2023-01-06 09:41 UTC, paigeh1 commented on SDG_NI.py
>  whole_NI_df = pd.read_csv(os.path.join(CWD, "data", "KS101NI.csv"),
Had discussion, will add in code where we remove commas and excess columns to make it more reproducible. Think there's a ticket for the commas issue.

2023-01-12 20:08 UTC, Antonio-John commented on SDG_NI.py
>  whole_NI_df = pd.read_csv(os.path.join(CWD, "data", "KS101NI.csv"),
This is where I am tripping up at the moment. I'm not sure the subsetted "," version is on sync yet. Let me know when it is and/or if the code to do this is available :)

2023-01-12 20:11 UTC, Antonio-John requested changes

2023-01-12 20:11 UTC, Antonio-John commented on data_transform.py
> +def convert_east_north(df, long, lat):
nice :)

2023-01-12 20:11 UTC, Antonio-John commented on requirements.txt
> +convertbng
downloaded fine :) not sure if we've talked about this before, does it matter which package version we use?

2023-01-13 08:57 UTC, nkshaw23 commented on SDG_NI.py
>  whole_NI_df = pd.read_csv(os.path.join(CWD, "data", "KS101NI.csv"),
updated dataset on sync (KS101NI.csv). Should load in with existing code so no new code needed. Can then remove 70-75 and just need to update dataset variable name to `census_df` so it can be plugged into the rest of the pipeline

2023-01-13 09:06 UTC, nkshaw23 commented on SDG_NI.py
> +stops_geo_df = di.geo_df_from_pd_df(pd_df=stops_df,
In `main` and `scotland` we load this dataset in a slightly different way. We have a `easting` and `northing` column in the dataset which we use (and the default EPSG in the config)

![image](https://user-images.githubusercontent.com/20166290/212280004-c595d132-ddf0-4285-a8a0-c1494fadcaf0.png)

Think we should do the same here for consistency - will make it much easier when combining scripts aswell. So rather than load in Lat and Long and convert, create the easting and northing columns for the data on sync (as we found we had to hard a copy) and load straight in.

Wonder if this will fix the slight misalignment issue aswell - but looking at conversations last week it seems we are happy to have note in the methods and accept this very small geospatial variance.

2023-01-19 21:29 UTC, Antonio-John commented on SDG_NI.py
>  whole_NI_df = pd.read_csv(os.path.join(CWD, "data", "KS101NI.csv"),
Thanks for updating the file on SYNC. Have now read this in as suggested and pipeline is behaving as expected.

2023-01-20 09:04 UTC, Antonio-John commented on SDG_NI.py
> +stops_geo_df = di.geo_df_from_pd_df(pd_df=stops_df,
Have made this change but would like to talk through this at some point :)

2023-01-20 09:42 UTC, Antonio-John commented on SDG_NI.py
> +stops_geo_df = di.geo_df_from_pd_df(pd_df=stops_df,
Revert back to using the lat/long coordinates. When the timetable data is read in for NI in the future, the script can be made more consistent to main/scotland at that point.

2023-01-20 10:27 UTC, paigeh1 commented on requirements.txt
> +convertbng
I think it's something we should think about in future and tagging all packages with a specific version

2023-01-20 12:07 UTC, Antonio-John approved these changes

2023-01-20 12:07 UTC, merged